# Generated by Django 5.2.1 on 2025-07-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='interested_places',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('broker', 'Broker'), ('buyer', 'Buyer'), ('investor', 'Investor')], default='buyer', max_length=20),
        ),
    ]
