# Generated by Django 5.2.1 on 2025-08-08 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_interested_places_profile_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='budget',
            field=models.CharField(blank=True, help_text='e.g. 50L-1Cr, 1Cr-2Cr, etc.', max_length=100, null=True),
        ),
    ]
